### ISSUE TITLE
How can I test ActivitiesApiTest ?

### ISSUE THREAD

**Issue by ishara** [strava/developers.strava.com#83]
I have generate java project using swagger-generator command 

swagger-codegen generate -i https://developers.strava.com/swagger/swagger.json -c config/android.json -l java -o generated/java

How can I add authentication for test case ?

I just run test case I am getting fallowing  error

io.swagger.client.ApiException: Unauthorized

	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:926)
	at io.swagger.client.ApiClient.execute(ApiClient.java:842)
	at io.swagger.client.api.ActivitiesApi.getLoggedInAthleteActivitiesWithHttpInfo(ActivitiesApi.java:876)
	at io.swagger.client.api.ActivitiesApi.getLoggedInAthleteActivities(ActivitiesApi.java:859)
	at io.swagger.client.api.ActivitiesApiTest.getLoggedInAthleteActivitiesTest(ActivitiesApiTest.java:150)

**Comment by mindy-stivers** [comment]
Hi @ishara, we're doing some cleanup in our github repository.

If you are still having trouble with this, could you please send an email to api@strava.com?

Thanks!
